export default function Head() {
  return (
    <>
      <title>Fajrul.id Website</title>
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
      <meta
        name="description"
        content="fajrul.id is a front-end web developer portfolio showcasing my personal projects and blog. If you have web related problems to solve then let&#x27;s work together!"
      />
      <meta
        name="keyword"
        content="muhammad fajrul amin,fajrul id,fajrulid, fajrulmyid, fajrulamin, fajrul, my, id, jvalley, indonesia, portfolio, javascript, developer ,fajrul,fajrul islam"
      />
      <meta property="og:locale" content="id_ID" />
      <meta
        property="og:title"
        content="Muhammad Fajrul Amin | ReactJs Web Developer"
      />
      <meta
        property="og:description"
        content="Muhammad fajrul amin. ReactJs Web Developer portfolio showcasing my personal projects and blog. If you have web related problems to solve then let&#x27;s work together!"
      />
      <meta property="og:image" content="https://fajrul.my.id/home-og.png" />
      <meta property="og:image:width" content="1200" />
      <meta property="og:image:height" content="630" />
      <meta property="og:image:type" content="image/jpg" />
      <meta property="og:url" content="https://fajrul.id" />
      <meta property="og:type" content="website" />
      <link rel="manifest" href="./assets/img/favicon/site.webmanifest" />
      <link
        rel="apple-touch-icon"
        sizes="180x180"
        href="./assets/img/favicon/apple-touch-icon.png"
      />
      <link
        rel="icon"
        type="image/png"
        sizes="32x32"
        href="./assets/img/favicon/favicon-32x32.png"
      />
      <link
        rel="icon"
        type="image/png"
        sizes="16x16"
        href="./assets/img/favicon/favicon-16x16.png"
      />
      <link
        rel="mask-icon"
        href="./assets/img/favicon/safari-pinned-tab.svg"
        color="#000000"
      />
      <link rel="shortcut icon" href="./assets/img/favicon/favicon.ico" />
    </>
  );
}
